# Generated by Django 6.0.5 on 2026-05-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
