# Generated by Django 6.0.5 on 2026-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_filme_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
